spring:
  application:
    name: loan-api

---
spring:
  config:
    activate:
      on-profile: oracle,default
  datasource:
    url: 'jdbc:oracle:thin:@//localhost:1521/FREEPDB1'
    username: '${DB_USER:app_user}'
    password: '${DB_PASSWORD:Welcome-12345}'
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true

---
spring:
  config:
    activate:
      on-profile: h2-oracle
  datasource:
    url: 'jdbc:h2:./data/loan-db;MODE=Oracle;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;AUTO_SERVER=TRUE'
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

springdoc:
  swagger-ui:
    path: /openapi-spec
    yaml: true
